create table if not exists locations (
  id bigint primary key,
  name text not null,
  state text not null,
  latitude double precision,
  longitude double precision,
  rainfall numeric default 0,
  soil_moisture numeric default 0,
  slope numeric default 0,
  historical_susceptibility numeric default 0,
  previous_risk numeric default 0,
  risk_score numeric default 0,
  risk_level text default 'LOW',
  roads numeric default 0,
  settlements numeric default 0,
  infrastructure numeric default 0,
  last_updated timestamp with time zone default now()
);

create table if not exists alerts (
  id bigint primary key,
  location_id bigint references locations(id),
  location_name text,
  state text,
  level text,
  score numeric,
  message text,
  timestamp text,
  status text default 'ACTIVE'
);

create table if not exists ai_insights (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  prompt text,
  response text,
  location_name text,
  score numeric,
  level text
);

create index if not exists idx_locations_risk on locations(risk_score desc);
create index if not exists idx_alerts_status on alerts(status);
