import {
  AlertTriangle,
  Bell,
  CheckCircle2,
  Clock,
  MapPin,
  ShieldAlert,
} from "lucide-react";

import { useAppStore } from "../store/appStore";
import { getRiskColor } from "../services/riskEngine";

export default function AlertCenter() {
  const { alerts, resolveAlert } = useAppStore();

  const activeAlerts = alerts.filter(
    (alert) => alert.status === "ACTIVE"
  );

  const acknowledgedAlerts = alerts.filter(
    (alert) => alert.status === "ACKNOWLEDGED"
  );

  const resolvedAlerts = alerts.filter(
    (alert) => alert.status === "RESOLVED"
  );

  const getAlertIcon = (level: string) => {
    if (level === "CRITICAL") {
      return <ShieldAlert size={18} />;
    }

    if (level === "HIGH") {
      return <AlertTriangle size={18} />;
    }

    return <Bell size={18} />;
  };

  const getAlertClass = (level: string) => {
    if (level === "CRITICAL") return "alert-critical";
    if (level === "HIGH") return "alert-high";
    return "alert-moderate";
  };

  return (
    <div className="main">
      {/* TOP BAR */}
      <div className="topbar">
        <div>
          <div className="eyebrow">SYSTEM MONITORING</div>
          <h1>Alert Center</h1>
          <p className="page-subtitle">
            AI-generated landslide risk warnings and response alerts
          </p>
        </div>

        <div className="topbar-status">
          <span className="status-dot"></span>
          Monitoring Active
        </div>
      </div>

      {/* ALERT SUMMARY */}
      <div className="stats-grid alert-stats">
        <div className="stat-card">
          <div className="stat-icon critical">
            <ShieldAlert size={20} />
          </div>

          <div>
            <span className="stat-label">ACTIVE ALERTS</span>
            <strong>{activeAlerts.length}</strong>
            <small>Require attention</small>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon warning">
            <AlertTriangle size={20} />
          </div>

          <div>
            <span className="stat-label">ACKNOWLEDGED</span>
            <strong>{acknowledgedAlerts.length}</strong>
            <small>Being monitored</small>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon safe">
            <CheckCircle2 size={20} />
          </div>

          <div>
            <span className="stat-label">RESOLVED</span>
            <strong>{resolvedAlerts.length}</strong>
            <small>Closed alerts</small>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon neutral">
            <Bell size={20} />
          </div>

          <div>
            <span className="stat-label">TOTAL ALERTS</span>
            <strong>{alerts.length}</strong>
            <small>Generated by system</small>
          </div>
        </div>
      </div>

      {/* ACTIVE ALERTS */}
      <div className="panel">
        <div className="panel-header">
          <div>
            <h2>Active Alerts</h2>
            <p>
              Automated warnings generated from current environmental
              conditions
            </p>
          </div>

          <div className="alert-live-indicator">
            <span className="status-dot"></span>
            LIVE
          </div>
        </div>

        {activeAlerts.length === 0 ? (
          <div className="empty-alerts">
            <CheckCircle2 size={42} />

            <h3>No Active Alerts</h3>

            <p>
              All monitored locations are currently below warning
              thresholds.
            </p>
          </div>
        ) : (
          <div className="alerts-list">
            {activeAlerts.map((alert) => (
              <div
                key={alert.id}
                className={`alert-card ${getAlertClass(alert.level)}`}
              >
                {/* ALERT HEADER */}
                <div className="alert-card-header">
                  <div className="alert-title-section">
                    <div
                      className="alert-level-icon"
                      style={{
                        color: getRiskColor(alert.level),
                      }}
                    >
                      {getAlertIcon(alert.level)}
                    </div>

                    <div>
                      <div className="alert-level">
                        {alert.level} RISK
                      </div>

                      <h3>{alert.locationName}</h3>

                      <div className="alert-location">
                        <MapPin size={13} />
                        {alert.state}
                      </div>
                    </div>
                  </div>

                  <div
                    className="alert-score"
                    style={{
                      borderColor: getRiskColor(alert.level),
                    }}
                  >
                    <span>RISK SCORE</span>

                    <strong>{alert.score}</strong>

                    <small>/100</small>
                  </div>
                </div>

                {/* ALERT MESSAGE */}
                <div className="alert-message">
                  <AlertTriangle size={16} />

                  <p>{alert.message}</p>
                </div>

                {/* ALERT FOOTER */}
                <div className="alert-card-footer">
                  <div className="alert-time">
                    <Clock size={14} />
                    Generated {alert.timestamp}
                  </div>

                  <button
                    className="resolve-button"
                    onClick={() => resolveAlert(alert.id)}
                  >
                    <CheckCircle2 size={15} />
                    Mark Resolved
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* ALERT HISTORY */}
      <div className="panel">
        <div className="panel-header">
          <div>
            <h2>Alert History</h2>
            <p>Previously generated warnings and their current status</p>
          </div>
        </div>

        {alerts.length === 0 ? (
          <div className="empty-alerts history-empty">
            <Bell size={36} />

            <h3>No Alert History</h3>

            <p>
              Alerts generated from the Simulation Center will appear
              here.
            </p>
          </div>
        ) : (
          <div className="alert-history-list">
            {alerts.map((alert) => (
              <div key={alert.id} className="history-row">
                {/* LOCATION */}
                <div className="history-location">
                  <div
                    className="history-icon"
                    style={{
                      color: getRiskColor(alert.level),
                    }}
                  >
                    {getAlertIcon(alert.level)}
                  </div>

                  <div>
                    <strong>{alert.locationName}</strong>

                    <span>
                      <MapPin size={12} />
                      {alert.state}
                    </span>
                  </div>
                </div>

                {/* RISK */}
                <div className="history-risk">
                  <span
                    className="risk-badge"
                    style={{
                      color: getRiskColor(alert.level),
                      borderColor: getRiskColor(alert.level),
                    }}
                  >
                    {alert.level}
                  </span>

                  <strong>{alert.score}/100</strong>
                </div>

                {/* TIME */}
                <div className="history-time">
                  <Clock size={13} />
                  {alert.timestamp}
                </div>

                {/* STATUS */}
                <div className="history-status">
                  {alert.status === "ACTIVE" && (
                    <span className="status-badge status-active">
                      <span className="status-dot"></span>
                      ACTIVE
                    </span>
                  )}

                  {alert.status === "ACKNOWLEDGED" && (
                    <span className="status-badge status-acknowledged">
                      <Bell size={13} />
                      ACKNOWLEDGED
                    </span>
                  )}

                  {alert.status === "RESOLVED" && (
                    <span className="status-badge status-resolved">
                      <CheckCircle2 size={13} />
                      RESOLVED
                    </span>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* ALERT SYSTEM INFORMATION */}
      <div className="alert-system-info">
        <div className="alert-system-icon">
          <Bell size={20} />
        </div>

        <div>
          <strong>Smart Alert Engine</strong>

          <p>
            Alerts are automatically generated when simulated or monitored
            environmental conditions produce a Moderate, High, or Critical
            landslide risk assessment.
          </p>
        </div>

        <div className="alert-engine-status">
          <span className="status-dot"></span>
          ENGINE ACTIVE
        </div>
      </div>
    </div>
  );
}